/*
account-model.js
**************************************
This file is responsible for defining the functions that interact with the database to manage account-related data. It imports the database connection pool from the "database/index.js" file and defines an asynchronous function called "registerAccount" that executes a SQL query to insert a new account record into the "account" table in the database. The function takes parameters for the user's first name, last name, email, and password, and returns the result of the query, which can be used to confirm that the account was successfully created or to handle any errors that may occur during the registration process. Additional functions for retrieving account information or managing user authentication can also be defined in this section as needed.
**************************************/



// Needed Resources
/***********************
This section imports the database connection pool from the "database/index.js" file. This allows the functions defined in this file to execute SQL queries against the database using the established connection pool, which manages multiple connections efficiently for handling concurrent database interactions.
***********************/

const pool = require("../database/")



// Model functions
/**********************************
 This section defines the model functions that interact with the database to retrieve inventory-related data. The "getClassifications" function is an asynchronous function that executes a SQL query to retrieve all classification data from the "classification" table in the database, ordered by the classification name. The function returns the result of the query, which can be used by other parts of the application to display or manipulate inventory data. Additional functions for retrieving inventory items by classification ID or inventory ID can also be defined in this section as needed.
***********************************/

// Register a new account
async function registerAccount(account_firstname, account_lastname, account_email, account_password) { // defines an asynchronous function named "registerAccount" that takes in parameters for the user's first name, last name, email, and password. This function is responsible for inserting a new user account into the database using the provided information. The function executes a SQL query to insert the new account data into the appropriate table in the database and returns the result of the query, which can be used to confirm that the account was successfully created or to handle any errors that may occur during the registration process.
    try {
        const sql = "INSERT INTO account (account_firstname, account_lastname, account_email, account_password, account_type) VALUES ($1, $2, $3, $4, 'Client') RETURNING *"  // defines a SQL query string that inserts a new record into the "account" table with the provided account information. The query uses parameterized placeholders ($1, $2, $3, $4) to safely insert the values for the first name, last name, email, and password into the database. The "RETURNING *" clause is included to return the newly created account record after the insertion is successful, allowing the application to confirm that the account was created and to access any additional information generated by the database (such as an auto-incremented ID).
        return await pool.query(sql, [account_firstname, account_lastname, account_email, account_password]) // uses the connection pool to execute the SQL query against the database. The query inserts a new account record with the provided first name, last name, email, and password. The "await" keyword is used to wait for the asynchronous operation to complete before proceeding. The function returns the result of the query, which can be used to confirm that the account was successfully created or to handle any errors that may occur during the registration process.
    } catch (error) { // catches any errors that occur during the execution of the SQL query and logs the error message to the console. This helps in debugging and ensures that any issues with the database operation are properly handled without crashing the application. The function also returns the error message, which can be used by other parts of the application to display an appropriate error message to the user or to take further actions based on the error.
        return error.message // returns the error message if an error occurs during the execution of the SQL query. This allows other parts of the application to access the error information and handle it accordingly, such as displaying an error message to the user or logging it for further analysis.
    }
}



// Export
/******************************
 * This section exports the functions defined in this file, making them available for use in other parts of the application. By exporting these functions, other modules can import and utilize them to perform database operations related to account management, such as registering new accounts or retrieving account information. This promotes modularity and separation of concerns within the application, allowing for better organization and maintainability of the codebase.
 ******************************/

module.exports = { registerAccount } // exports an object that contains the "registerAccount" function. This allows other parts of the application to import and use this function to register new accounts in the database when needed.